/**
 * Search action types.
 */
export const SEARCH_LISTING_LOADING_START = 'SEARCH_LISTING_LOADING_START';
export const GET_SEARCH_LIST = 'GET_SEARCH_LIST';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_DATA = 'CLEAR_DATA';
export const STOP_LOADING = 'STOP_LOADING';
export const PAGINATING_LOADING_START ='PAGINATING_LOADING_START';
export const GET_PAGINATED_SEARCH_LIST = 'GET_PAGINATED_SEARCH_LIST';
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';